### PR TITLE
Fix under-alignment issues

### PR DESCRIPTION
**Pull request by improbablejan**
Fixes https://github.com/cameron314/concurrentqueue/issues/177

### CODE REVIEW

**Comment by cameron314** [comment]
It looks like we can't use `aligned_storage` (I support VS2013 for now): https://stackoverflow.com/q/24045850/21475.
Can we just move the `MOODYCAMEL_ALIGNAS` to the declaration of `elements` instead of `Block`? I think that would be sufficient.

**Comment by improbablejan** [comment]
Shame. Yeah, I'll move it.

**Comment by cameron314** [comment]
Thanks for the PR!

**Comment by improbablejan** [comment]
No worries, thanks for the quick turnaround.

**Pull request merged**
