### PR TITLE
Added MOODYCAMEL_DELETED_FUNCTION macro (compiling under VS2012 now works)

### PR DESCRIPTION
**Pull request by jlaumon**

### CODE REVIEW

**Comment by cameron314** [comment]
Awesome, looks good.

**Comment by cameron314** [comment]
Hmm, wait, the tests don't compile. I'll fix it.

**Comment by cameron314** [comment]
I got everything to compile and run. The unit test for exception handling doesn't pass. I'm looking into it.

**Comment by cameron314** [comment]
OK, the unit test for exception handling *sometimes* passes, and *sometimes* fails. The thing is, that part of the test is *not* threaded, meaning there's either a compiler bug or I'm invoking undefined behaviour somewhere (otherwise the result of the test should be deterministic).

**Comment by cameron314** [comment]
Ah, `MOODYCAMEL_NOEXCEPT_CTOR` was true when it shouldn't have been. Apparently `std::is_nothrow_move_constructible` is buggy in VS2012 (it yields the right value in VS2013).

**Comment by jlaumon** [comment]
Great! Thanks! 
Sorry for letting you do all the hard work.

**Comment by cameron314** [comment]
No worries. Might be a good idea to run the tests first next time though :-)

**Pull request merged**
