### PR TITLE
Added CMake support.  Only tested on Linux (Ubuntu).

### PR DESCRIPTION
**Pull request by zerodefect**
Added cmake support.  Tested on Ubuntu Linux (17.04) using gcc.  Any other non-Linux platform or compiler variation will need a tiny bit of work to get it going.

In addition, cmake script now has a 'make install' target (which the current make targets don't have). On my system, concurrentqueue.h and blockingconcurrentqueue.h are installed to a directory in /usr/local/include/moodycamel.

### CODE REVIEW

**Comment by zerodefect** [comment]
...and I'd welcome someone who is able to test (and/or add support) for the likes of clang, mingw (and Windows).

**Comment by cameron314** [comment]
Hmm. Is there a way to fit all the cmake files under `build/`?

**Comment by zerodefect** [comment]
Honestly, that wouldn't really be in the spirit of cmake.  Take a look at this very simple [example](https://cmake.org/examples/).

**Comment by zerodefect** [comment]
The other point that I forgot to make - using CMake it's possible to generate the VS and XCode projects without having to maintain them explicitly.

**Comment by zerodefect** [comment]
I'll revisit this once I get my other branch merged. I ended up tripping over my own feet attempting to use new git client.

**Pull request closed without merging**
