### PR TITLE
Adding support for super-aligned types

### PR DESCRIPTION
**Pull request by narrill**
This replaces the `static_assert` preventing super-aligned types from being used with one that prevents types with an alignment greater than their size from being used, sets `Block`'s alignment equal to `T`'s, adds `aligned_malloc` and `aligned_free` to `ConcurrentQueueDefaultTraits`, and adds specializations of `create`, `create_array`, `destroy`, and `destroy_array` for super-aligned types that use them.

### CODE REVIEW

**Comment by cameron314** [comment]
There still needs to be an assert for at least the case where the alignment is greater than the size of the object, otherwise it's impossible to create aligned arrays of those objects.

**Comment by narrill** [comment]
Done 👍

**Comment by sasq64** [comment]
What happened with this?
Applying this fix lets me use `std::function` in the shared object on iOS.

**Comment by cameron314** [comment]
Sorry I'm slow. Better late than never? :-)

**Pull request merged**
