### PR TITLE
Fix ordered list formatting in README.md

### PR DESCRIPTION
**Pull request by jplatte**
Have a look at the "rich diff" (document icon in the header of the README.md diff view) instead of the code diff to see how the generated HTML changes.

### CODE REVIEW

**Comment by cameron314** [comment]
Ah, good catch, thanks!

I think it's the blank line you added (and not the `1`s) that makes all the difference, though --  markdown is supposed to accept increasing digits as an ordered list.

I'll gladly accept the pull request if you change the numbers back to sequentially increasing ones (for those that read the README as plain text).

**Comment by jplatte** [comment]
I know the blank line was the important change, just thought only 1s would make editing simpler. I'll change it back if you don't want it.

**Comment by jplatte** [comment]
Okay, I rewrote the commit now (didn't want to have two commits around for this tiny change).

**Comment by cameron314** [comment]
Awesome, thanks!

**Pull request merged**
