### PR TITLE
Enable use of standard thread ids

### PR DESCRIPTION
**Pull request by jupp0r**

### CODE REVIEW

**Comment by cameron314** [comment]
Hi! Thanks for the pull request, but I can't integrate it as-is.
The reason I didn't use std::thread_id_t in the first place is that I need two special distinct values that cannot clash with real thread IDs (you seem to set both of them to zero by not explicitly initializing them). Unfortunately, std::thread_id_t is allowed to contain any implementation-defined value, so I can't rely on e.g. 0 and 1 being invalid IDs. That was the sole reason I went with a TLS-based solution in the general case.

Apart from that, have you tried running the benchmarks with and without your modifications? Is there any significant difference performance-wise?

**Comment by jupp0r** [comment]
Hi,
> On 16 Oct 2015, at 19:37, Cameron <notifications@github.com> wrote:
> 
> Hi! Thanks for the pull request, but I can't integrate it as-is.
> The reason I didn't use std::thread_id_t in the first place is that I need two special distinct values that cannot clash with real thread IDs (you seem to set both of them to zero by not explicitly initializing them). Unfortunately, std::thread_id_t is allowed to contain any implementation-defined value, so I can't rely on e.g. 0 and 1 being invalid IDs. That was the sole reason I went with a TLS-based solution in the general case.
According to the standard (http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2012/n3485.pdf), default-initialised thread ids should never compare true to ids representing actual threads:

> id() noexcept;
> 
> Effects: Constructs an object of type id. 
> 
> Postconditions: The constructed object does not represent a thread of execution.

is there a way to get around the two distict invalid values problem?

> Apart from that, have you tried running the benchmarks with and without your modifications? Is there any significant difference performance-wise?
I'm porting the benchmarks to the platform I'm targeting, takes some time.

Jupp

**Comment by cameron314** [comment]
Ah, neat, didn't know that about the default value. The second invalid value is only required when `MOODYCAMEL_CPP11_THREAD_LOCAL_SUPPORTED` is true, which is currently permanently disabled because of reported bugs with it on (which I cannot reproduce locally yet).

Definitely worth getting the benchmarks to compile on your platform, but even more important, I think, are the unittests. Sorry if they're hard to port! I assumed a fully C++11 compliant compiler everywhere, and a few other platform-specific things (cpuinfo comes to mind).

**Comment by jupp0r** [comment]
> On 16 Oct 2015, at 22:56, Cameron <notifications@github.com> wrote:
> 
> Ah, neat, didn't know that about the default value. The second invalid value is only required when MOODYCAMEL_CPP11_THREAD_LOCAL_SUPPORTED is true, which is currently permanently disabled because of reported bugs with it on (which I cannot reproduce locally yet).
Ok, so that should work, sweet.

> Definitely worth getting the benchmarks to compile on your platform, but even more important, I think, are the unittests. Sorry if they're hard to port! I assumed a fully C++11 compliant compiler everywhere, and a few other platform-specific things (cpuinfo comes to mind).
I'm building for numerous platforms, but clang 3.7 + arm causes most problems.

I'll keep you posted on the benchmarks + tests.

Jupp

**Comment by cameron314** [comment]
Cool, thanks!

**Comment by cahlbin** [comment]
@jupp0r any updates on this issue? Thanks

**Comment by jupp0r** [comment]
I'm currently using a platform independent workaround that builds on your idea of hashing an tls slot address. It currently relies on boost::thread_specific_ptr which works pretty much everywhere. I guess you would not want to depend on boost :). I'll look into the boost code to see how they do thread local storage on OSX/iOS and follow up next week.

**Comment by cameron314** [comment]
I'm closing this request since I just pushed a similar commit, with the main difference being that std::thread::id is not used for all platforms, only iOS (mostly for performance reasons, on Windows it's pretty slow, for example).

Thanks for your work!

**Pull request closed without merging**
