### PR TITLE
Fix collision with crtdbg.h

### PR DESCRIPTION
**Pull request by cmaughan**
On windows, if you include concurrentqueue after crtdbg.h, it breaks because malloc/free has been #define'd to something else.   The underscore is just a suggestion - but any other name for the malloc/free, and calling the 'malloc' without 'std::malloc' stops the redefined malloc from breaking (i.e. on windows, it ends up calling std::_crt_malloc, or whatever, which isn't in the std namespace ;)

### CODE REVIEW

**Comment by cameron314** [comment]
Hmm. Seems more like a bug with crtdbg.h to me, since it breaks perfectly valid standard code :-(
Changing the name of `Traits::malloc` is a breaking API change. I'll see if there's something else I can do.

**Comment by cameron314** [comment]
Thanks for finding this by the way!

**Comment by cmaughan** [comment]
No problem!  The popular stb nothings library does it in a similar way by using a different named malloc:

#if defined(STBI_MALLOC) && defined(STBI_FREE) && defined(STBI_REALLOC)
// ok
#elif !defined(STBI_MALLOC) && !defined(STBI_FREE) && !defined(STBI_REALLOC)
// ok
#else
#error "Must define all or none of STBI_MALLOC, STBI_FREE, and STBI_REALLOC."
#endif

#ifndef STBI_MALLOC
#define STBI_MALLOC(sz)    malloc(sz)
#define STBI_REALLOC(p,sz) realloc(p,sz)
#define STBI_FREE(p)       free(p)
#endif

**Comment by cmaughan** [comment]
https://github.com/nothings/stb

**Comment by cameron314** [comment]
I've committed a workaround that should fix this problem. Let me know if it does the trick!

**Comment by tojocky** [comment]
Could you please close this PR if the issue resolved?

**Comment by cameron314** [comment]
I'll close for now, as far as I can tell my commit fixed the problem.

**Pull request closed without merging**
